name: pausable_timer
description: A timer implementation that can be paused, resumed and reset.
homepage: https://github.com/llucax/pausable_timer
repository: https://github.com/llucax/pausable_timer

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clock: ^1.1.0

dev_dependencies:
  coverage: ^1.0.2
  test: ^1.16.0
  fake_async: ^1.2.0
  lints: ^1.0.1
